# Generated by Django 2.2 on 2019-04-04 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True, max_length=30, primary_key=True, serialize=False
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True, max_length=30, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=128)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="workspaces.Team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True, max_length=30, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=128)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="workspaces.Team",
                    ),
                ),
            ],
        ),
    ]
