# Generated by Django 2.2 on 2019-05-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("workspaces", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="suffix",
            field=models.CharField(blank=True, default="", max_length=128),
        )
    ]
