# Generated by Django 2.2 on 2019-05-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("workspaces", "0002_user_suffix")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_permissions",
            field=models.BooleanField(default=False),
        )
    ]
