# Generated by Django 2.2 on 2019-05-12 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("polls", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="userchoice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        )
    ]
