# Generated by Django 2.2 on 2019-05-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_userchoice_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userchoice',
            options={'ordering': ('created_at',)},
        ),
    ]
