# Generated by Django 2.2.1 on 2019-06-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("polls", "0003_auto_20190512_1922")]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="unique_choice",
            field=models.BooleanField(default=False),
        )
    ]
