# Generated by Django 2.2.1 on 2019-07-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("polls", "0004_poll_unique_choice")]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="poll",
            name="visible_results",
            field=models.BooleanField(default=True),
        ),
    ]
